# Generated by Django 4.1.5 on 2023-01-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rull',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
