# Generated by Django 4.1.5 on 2023-01-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_rull'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rull',
            new_name='rule',
        ),
    ]
